### ISSUE TITLE
GameManager Integration

### ISSUE THREAD

**Issue by ambarket** [ambarket/botbattle#18]
Some issues I found are listed below.

1) The tiles are never changed, each time a tile is used it should be replaced with a new one. Hopefully this will be a quick fix.

2) Theres something very wrong with the attack and defend animation JSOn that is being sent. Play bot v bot game a few times to see what I mean. I'm pretty sure its right on the client side, havent looked into the GameManager code for it yet.

2) When the game ends due to invalid bot move, the final json state sent is identical to the previous state because updateBoard was never called. 

This is a bigger problem that I wanted to take some time to flesh out a good solution since it involved changing the game loop and interface to make sure the JSON is always whats expected.

1) Add a getInitialGamestate() method to the GameInterface. This function must setup the board for a new game, then construct and return a valid initialGamestate. For saveTheIsland this can have no animatableEvents or debugData, just a gameData object with the initial tiles and a turn description saying the game has started.

2) Add a getFinalGamestate method to the GameInterface. This function must construct and send a valid finalGameState. For saveTheIsland this can have no animatableEvents or debugData, just a gameData object with the tiles at the end of the game and a turnDescription set to either "Player X has won!" or "Player Y has been disqualified due to invalid move". 

3) Change the existing getJSONStringForThisTurn function to getMidGamestate(). This function then can always assume updateBoard was run before it so lastMove, lastPlayersTurn, lastBoard will always be relevant.

**Comment by Stevenpc3** [comment]
I recall endPosition and startPosition are set as “endposition” and “startposition” in the game manager.  This just needs to fixed.






From: ambarket
Sent: ‎Sunday‎, ‎April‎ ‎12‎, ‎2015 ‎11‎:‎31‎ ‎PM
To: ambarket/botbattle





Some issues I found are listed below.

1) The tiles are never changed, each time a tile is used it should be replaced with a new one. Hopefully this will be a quick fix.

2) Theres something very wrong with the attack and defend animation JSOn that is being sent. Play bot v bot game a few times to see what I mean. I'm pretty sure its right on the client side, havent looked into the GameManager code for it yet.

2) When the game ends due to invalid bot move, the final json state sent is identical to the previous state because updateBoard was never called. 

This is a bigger problem that I wanted to take some time to flesh out a good solution since it involved changing the game loop and interface to make sure the JSON is always whats expected.

1) Add a getInitialGamestate() method to the GameInterface. This function must setup the board for a new game, then construct and return a valid initialGamestate. For saveTheIsland this can have no animatableEvents or debugData, just a gameData object with the initial tiles and a turn description saying the game has started.

2) Add a getFinalGamestate method to the GameInterface. This function must construct and send a valid finalGameState. For saveTheIsland this can have no animatableEvents or debugData, just a gameData object with the tiles at the end of the game and a turnDescription set to either "Player X has won!" or "Player Y has been disqualified due to invalid move". 

3) Change the existing getJSONStringForThisTurn function to getMidGamestate(). This function then can always assume updateBoard was run before it so lastMove, lastPlayersTurn, lastBoard will always be relevant.

**Comment by ambarket** [comment]
Fixed that already

**Comment by ambarket** [comment]
I  pushed my latest stuff to a new branch. Ill leave it running at https://ambarket.info:6058 in case you want to look at it quick and test it without having to pull.

**Comment by Akiira** [comment]
The tiles are changing correctly on my side and the JSON being sent out represents this.
Here are two json strings that ArenaGameManager sends out:
{
=       "messagetype": "gamestate",
=       "type": "midGame",
=       "enableHumanInput": "player1",
=       "animatableEvents": [
=               {
=                       "event": "move",
=                       "data": {
=                               "player": 2,
=                               "endposition": 24,
=                               "startposition": 19
=                       }
=               }
=       ],
=       "gameData": {
=               "player1Tiles": [
=                       3,
=                       2,
=                       2,
=                       2,
=                       3
=               ],
=               "player2Tiles": [
=                       1,
=                       4,
=                       3,
=                       1,
=                       2
=               ],
=               "turnDescription": "Player 2 moves forward 5 spaces."
=       },
=       "debugData": {
=               "stderr": [
=                       "None"
=               ],
=               "stdout": [
=                       "move;5"
=               ]
=       }
=}

{
=       "messagetype": "gamestate",
=       "type": "midGame",
=       "enableHumanInput": "player2",
=       "animatableEvents": [
=               {
=                       "event": "move",
=                       "data": {
=                               "player": 1,
=                               "endposition": 3,
=                               "startposition": 6
=                       }
=               }
=       ],
=       "gameData": {
=               "player1Tiles": [
=                       1,
=                       2,
=                       2,
=                       2,
=                       3
=               ],
=               "player2Tiles": [
=                       1,
=                       4,
=                       3,
=                       1,
=                       2
=               ],
=               "turnDescription": "Player 1 moves forward 3 spaces."
=       },
=       "debugData": {
=               "stderr": [
=                       "None"
=               ],
=               "stdout": [
=                       "move;3"
=               ]
=       }
=}

Player 1 used a 3 tile to move forward and it was taken out and replaced with a one. So this problem may not be on my end.

As for the attack and defend animation, here is a json that the manager sends out during an attack:
{
=       "messagetype": "gamestate",
=       "type": "midGame",
=       "enableHumanInput": "player2",
=       "animatableEvents": [
=               {
=                       "event": "move",
=                       "data": {
=                               "player": 1,
=                               "endposition": 9,
=                               "startposition": 13
=                       }
=               },
=               {
=                       "event": "successfulAttack",
=                       "data": {
=                               "player": 2,
=                               "endposition": 14,
=                               "startposition": 19
=                       }
=               }
=       ],
=       "gameData": {
=               "player1Tiles": [
=                       1,
=                       2,
=                       2,
=                       2,
=                       4
=               ],
=               "player2Tiles": [
=                       2,
=                       4,
=                       3,
=                       1,
=                       2
=               ],
=               "turnDescription": "Player 1 attacks with one 5 tile."
=       },
=       "debugData": {
=               "stderr": [
=                       "None"
=               ],
=               "stdout": [
=                       "attack;5"
=               ]
=       }
=}

Based on my recollection, I thought the attack animation required a movement up to the attack position and then a "succesfulAttack" animation with the start an end position of the victim. And I thought the defended attack was the same except the second animation has the event name "defendedAttack" and has the start and end position of the attacker. If my understanding of it was incorrect or the requirements were changed let me know so I can update the code.

The 3rd item is just the fault of an incorrect ordering on the if statements in the getType function. I can simply reorder them and it will set the type to "final" in this case.

I'm not sure I understand the last 3 points. Initial and final states already do not have animated events, even though I thought I was told it did not really matter since any extra information would just be ignored. If this was incorrect it would be easy enough to just put an if statement in the function that already existed and use that to ensure there is no additional data in the JSON. Let me know if I should make this change.

On a side note, I saw in the commit somthing that I had questions about. Why are we changing the requirements for the humanInputValidation JSON string? All those extra fields seem unneeded since that JSON string will only ever be used for human players. I now see in the commit message we are now sending it for both bots and humans, perhaps my question should be why are we changing it so that we send it for both humans and bots?

**Comment by ambarket** [comment]
The problem was that the bots invalid move was never sent to the client. So
the user would have no idea why the game stopped. I fixed all these things
in the other branch. Also it just makes sense to format a nice message with
which player messed up and why.

I realized the tiles were changing they are just not animated and change so
quickly that it's hard to tell.

as for the rest maybe I didn't understood your code correctly in some
places and made much more drastic changes than necessary. I kinda thought
that, that's why I pushed to a separate branch in case you think it should
be rolled back but I kind of like the idea of having three separate
interface functions for each type of game state. I think it makes the logic
a lot easier to read.

**Comment by ambarket** [comment]
For the successful and defended attack, we need an array of three game states. First the attacker moves to one spot away from the defender. Then the successfulAttack or defendedAttack in which the start and endposition should be the same and are actually completely ignored on our end. Finally there should be a fallback event. If it was defended this will be the attacker falling back to their original position. If it was successful this will be the defender falling to the position it was hit to.
