### ISSUE TITLE
Player who wins?

### ISSUE THREAD

**Issue by Stevenpc3** [ambarket/botbattle#19]
If player 2 walks off the edge then the server reports that player 2 won.

**Comment by Stevenpc3** [comment]
same the other way... if one walks off it says player 2 won.  Must just be something swapped.

**Comment by ambarket** [comment]
This is because of an oversight I made. Can be fixed easily by allowing the
game class itself to send who won/ was disqualified when the game loop asks
for the final game state.

I also just realized that the solution we came up with earlier of sending
the animatable event of the last move in the final game state will probably
be a duplicate if the game ended due to disqualification. That's why I was
trying to separate them in the first place. This logic still needs to be
fleshed out.

**Comment by ambarket** [comment]
I believe this is fixed now.
