### ISSUE TITLE
Remove association of sessions with test arena

### ISSUE THREAD

**Issue by Stevenpc3** [ambarket/botbattle#7]
Move id association time to upload event
Flatten folder by just using id instead of session id

now log in is separated from test arena and test arena is anonymous in regard to user ultimately tracking games instead of tabs and browsers.

upload acts a refresh and must send the old id to remove the id and info on the server side then send the new id.

Also, make client side immed. invoke function a named function to "reset" the gameboard when upload is clicked.  Do not clear file selection unless radio button changes like currently done.

start the timeout when the upload is done.

**Comment by ambarket** [comment]
Based on what I've heard I think this is complete. Not sure about the reset functionality though.

**Comment by Stevenpc3** [comment]
Yeah, the problem was in the middle of a game or after that the board would need to be reset to initial position, but I guess on start of a new game we could have the server send the client an initialization command. The not clear the file selection I think happens by default. I have it clear it out when the radio button changes.

**Comment by Stevenpc3** [comment]
I don't know what our approach to the reset is.  I think we figured to just make the reset we run at start a callable function and add what would need to be add to it make it work.  The problem is that is game specific and we need the initial character positions and such to do that so we will have to implement a reset in that game.js and call it from testArena.js.  That also means that we need a interface for the game.js like we have for Game.java to ensure any new games implement the needed functions.

**Comment by ambarket** [comment]
This is going to take some discussion but here's what I propose.

On page load: -- TEST_ARENA.initializeCanvasOnPageLoad()
* The canvas is set in the TEST_ARENA object
* TEST_ARENA.resizeCanvas() is called
* window.onresize is registered. 
* The canvas is initialized to a white screen that says "upload bots to continue". 
* TEST_ARENA.state is set to 'pageLoaded' 

After upload: -- TEST_ARENA.initializeCanvasAfterUpload()
* The canvas message is set to "click play game to continue". 
* TEST_ARENA.state is set to 'uploaded' . 

After clicking start: -- TEST_ARENA.loadingScreen()
* TEST_ARENA.resetGameStateQueue() is called.
* The canvas message changes to "Loading..." until the initial game state is received. 
* TEST_ARENA.state is set to 'loading' 

I propose adding a property to all gameStates that is called type and will have the values 'initial', 'playing', or 'final'. Then in TEST_ARENA.gameStateQueue.processNextGameState() we will check for these type values and perform the additional special processing needed on the initial and final states as described below.

After receiving the initialGameState: 
* Call GAME.resetGameboard. This is async so the rest will probably be in that callback. 
* Change "Play Game" button to "Kill Game".
* Set TEST_ARENA.state === 'playing'
* Now call the draw function we have that recursively calls GAME.drawer.drawBoard(), then registers itself again with requestAnimationFrame(draw). 
** However add a check here for TEST_ARENA.state === 'playing'. So if the state is anything else, the draw is not re-registered.
* Finally pass any animateableEvents, gameData, and debugData in the initialGameState to GAME.

After receiving an intermittant 'playing' gameState
* Just pass along the animatableEvents, gameData, and debugData to GAME

After receiving the finalGameState:
* Pass any animatableEvents, gameData, and debugData to GAME
* Set TEST_ARENA.state === 'ended'. (So draw runs at most one more time)
* Change "Kill Game" button to "Play Game". (At this point the GameManager will have killed itself because it would know it was done).


This got quite complicated as I thought about it. I'm open for suggestions on how to make it less complicated.

**Comment by Stevenpc3** [comment]
Done.
