### ISSUE TITLE
Test Arena

### ISSUE THREAD

**Issue by Akiira** [ambarket/botbattle#8]
I was looking at code and commits for the test arena branch and noticed that we are probably going to be communicating with the game manager through stdin and stdout. I was under the impression the test arena input and output would be through a separate process, thus the reason for the Player class to have getters for its stdin and stdout. 

Refactoring the code for game manager to use stdin and stdout would not be too difficult but perhaps it would be easier if the TestArena just had its own dedicated game manager. That way GameManager can stay specialized for tournaments and we can more easily do the TestArena. 

I wrote up a ArenaGameManager class and an ArenaGameInstance class that should be much easier to use. It always sends the games HTML to stdout (I assume this is what you need on your end) and reads from stdin for the humans move.

If there is additionally functionality or constraints that are needed on these classes, or if I have misunderstood what is needed from the game managers let me know and I will fix them.

**Comment by Stevenpc3** [comment]
Thank you. I haven't looked at it yet though. To be honest I'm not sure. I was just testing that the game runs and that I could talk to it. I guess the idea was stdin and stdout. I'm not sure how else to do it between pant and child. I guess it can send messages. I have to talk to Austin today about it. We planned on socket io originally too then abandoned it (for server client Com), but I think it's the only way now. I may have went of track though.


-------- Original message --------

**Comment by ambarket** [comment]
Server to client communication will work with periodic ajax requests from client and a queue of game states in the server's testArenaInstance associated with that game. 

For the server to gameManager communication the original plan as I remember it was something like the following...

For bot v bot test arena. Everything is the same as a tournament game with the added requirement that the game states are sent over stdout. I was thinking that even though we could run the entire game before sending the results back to the client this may not be ideal since these games could potentially take a good amount of time to run. E.g. with bots that just move back and forth forever always applying the most defensive strategy. Instead we may want to just send every single turn via stdout immediately as its generated, that way people can see immediately what their bots are doing and will kill the game early if its not worth watching to the end. Also sending out immediately will probably simplify the subclassed GameResults object specified below.

For human v bot. I think this can be implemented with the same exact logic as bot v bot with a few simple changes
* subclass of Player that is HumanPlayer (To make things clean the current player should be extended into a subclass for BotPlayer). 
* This HumanPlayer will use the GameManager stdin and its own stdin, and have an unlimited timeout. And will have an overloaded implementation of sendBoardToPlayer (or whatever its called), that simply does nothing with it.
* Not sure how the timeout was done but this would require it to be an attribute of the Player objects, not the GameInstance. Presumably that wouldn't be too hard to change though.

Only change left then is to make the GameInstance send results over stdout. My thought was to subclass GameResult to ArenaGameResult (Or whatever you're using to store the saved GameStates for tournaments) This subclass would overload saveGameState (or whatever its called) to just send the game states over stdout as they're received instead of storing them in some data structure for later use. 

This way the main game loop in GameInstance doesn't change. All that changes is the concrete types of the Player objects and GameResults object that the GameInstance uses.

Also as part of the initial command line arguments (or just one JSON argument) we had specified that a boolean flag (or String for easier readability) would be passed indicating whether it is to run a Tournament or just a Test Arena instance. Based on that flag it would then read the rest of the arguments and interpret them. 

I haven't read the code so I don't know how far away this is from what is implemented and it very well may make more sense to just use different version of GameManager and GameInstance for the arena.

**Comment by Stevenpc3** [comment]
I think we have made it far enough to close this.
